## Automatically generated by odin 1.5.10 - do not edit
model_sr_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "model_sr_rhs_dde",
      rhs_desolve = "model_sr_rhs_desolve",
      initmod_desolve = "model_sr_initmod_desolve",
      output_dde = "model_sr_output_dde"),
    dll = "mmsu",
    user = c("a", "A_r0", "A_s0", "b", "cA", "cD", "cT", "D_r0", "D_s0",
             "Ev_r0", "Ev_s0", "ft", "init_res", "Iv_r0", "Iv_s0", "m", "mu",
             "n", "phi", "rA", "rD", "res_time", "resistance_dur_mult",
             "resistance_trans_mult", "rT_r_true", "rT_s", "S0", "Sv0",
             "T_r0", "T_s0", "toff", "ton"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("model_sr_rhs_dde", package = "mmsu")
        .C("model_sr_rhs_desolve", package = "mmsu")
        .C("model_sr_initmod_desolve", package = "mmsu")
        .C("model_sr_output_dde", package = "mmsu")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("model_sr_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "mmsu")
    },

    update_metadata = function() {
      meta <- .Call("model_sr_metadata", private$ptr,
                    PACKAGE = "mmsu")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("model_sr_create", user, PACKAGE = "mmsu")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/model_sr.json", mustWork = TRUE,
                             package = "mmsu")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("model_sr_set_user", private$ptr, user, PACKAGE = "mmsu")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("model_sr_initial_conditions", private$ptr, t, PACKAGE = "mmsu")
    },

    rhs = function(t, y) {
      .Call("model_sr_rhs_r", private$ptr, t, y, PACKAGE = "mmsu")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("model_sr_contents", private$ptr, PACKAGE = "mmsu")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_delay(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


model_sr <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("model_sr")
  model_sr_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(model_sr) <- "odin_generator"
attr(model_sr, "generator") <- model_sr_
model_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "model_rhs_dde",
      rhs_desolve = "model_rhs_desolve",
      initmod_desolve = "model_initmod_desolve",
      output_dde = "model_output_dde"),
    dll = "mmsu",
    user = c("a", "A_r0", "A_s0", "b", "cA", "cD", "cT", "D_r0", "D_s0",
             "Ev_r0", "Ev_s0", "ft", "init_res", "Iv_r0", "Iv_s0", "m", "mu",
             "n", "phi", "rA", "rD", "res_time", "resistance_dur_mult",
             "resistance_trans_mult", "rT_r_true", "rT_s", "S0", "Sv0",
             "T_r0", "T_s0", "toff", "ton"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("model_rhs_dde", package = "mmsu")
        .C("model_rhs_desolve", package = "mmsu")
        .C("model_initmod_desolve", package = "mmsu")
        .C("model_output_dde", package = "mmsu")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("model_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "mmsu")
    },

    update_metadata = function() {
      meta <- .Call("model_metadata", private$ptr,
                    PACKAGE = "mmsu")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("model_create", user, PACKAGE = "mmsu")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/model.json", mustWork = TRUE,
                             package = "mmsu")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("model_set_user", private$ptr, user, PACKAGE = "mmsu")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("model_initial_conditions", private$ptr, t, PACKAGE = "mmsu")
    },

    rhs = function(t, y) {
      .Call("model_rhs_r", private$ptr, t, y, PACKAGE = "mmsu")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("model_contents", private$ptr, PACKAGE = "mmsu")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_delay(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


model <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("model")
  model_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(model) <- "odin_generator"
attr(model, "generator") <- model_
